name: Release

on:
  push:
    branches: [ "main" ] 
  workflow_dispatch:

jobs:
  build-tauri:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          
      # - name: Install dependencies for Linux
      #   if: matrix.platform == 'ubuntu-latest'
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev libsoup-3.0-dev
          
      - name: Install dependencies for macOS
        if: matrix.platform == 'macos-latest'
        run: |
          brew install create-dmg
          
      - name: Install project dependencies
        run: npm install
          
      - name: Build the app
        run: npm run tauri build
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.platform }}
          path: src-tauri/target/release/bundle